// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxdRYFNQKlip5InpCtQv4vT8E1nHFMqxw',
    appId: '1:821995884235:web:d197ee610befaa44da954e',
    messagingSenderId: '821995884235',
    projectId: 'nepstocky',
    authDomain: 'nepstocky.firebaseapp.com',
    storageBucket: 'nepstocky.firebasestorage.app',
    measurementId: 'G-9HBT0MCJS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwRM3VlWWj_yVefjnKiq8z5THyH9Z_29Y',
    appId: '1:821995884235:android:462e1e41b384f154da954e',
    messagingSenderId: '821995884235',
    projectId: 'nepstocky',
    storageBucket: 'nepstocky.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGk2P7sNoZxt5vK7jOsuiuWwBEKj7OlD4',
    appId: '1:821995884235:ios:8a8512d2e89c32cfda954e',
    messagingSenderId: '821995884235',
    projectId: 'nepstocky',
    storageBucket: 'nepstocky.firebasestorage.app',
    iosBundleId: 'com.example.inventorymanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGk2P7sNoZxt5vK7jOsuiuWwBEKj7OlD4',
    appId: '1:821995884235:ios:8a8512d2e89c32cfda954e',
    messagingSenderId: '821995884235',
    projectId: 'nepstocky',
    storageBucket: 'nepstocky.firebasestorage.app',
    iosBundleId: 'com.example.inventorymanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxdRYFNQKlip5InpCtQv4vT8E1nHFMqxw',
    appId: '1:821995884235:web:32dfef41e0bd1504da954e',
    messagingSenderId: '821995884235',
    projectId: 'nepstocky',
    authDomain: 'nepstocky.firebaseapp.com',
    storageBucket: 'nepstocky.firebasestorage.app',
    measurementId: 'G-GCFB3WQDF2',
  );
}
